name: Pull Request Pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Deploy name
        env:
          CHANNEL_NAME: ${{ format('todo-list {0}', github.head_ref)}}
        run: echo "CHANNEL_NAME: $CHANNEL_NAME"

      - name: Build Application
        env: 
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
          REACT_APP_BASE_URL: https://todo-app-4104e--pr1-development-l1vboljb.web.app
        run: npm run build
        
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: deployment
        env: 
          CHANNEL_NAME: ${{ format('todo-list {0}', github.head_ref)}}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODO_APP_4104E }}'
          projectId: ${{ secrets.REACT_PROJECT_ID }}
          channelId: ${{ env.CHANNEL_NAME }}

      - name: Print deployment url
        env:
          URL: ${{ steps.deployment.outputs.details_url }}
        run: |
          echo "URL: $URL"